### ISSUE TITLE
Timeline recorders not being set - flaky behavior

### ISSUE THREAD

**Issue by guidezpl** [flutter/devtools#1706]
With 'Show Frames' checked, the timeline remains empty. The pause and re-record buttons have no effect.

![Screenshot 2020-03-09 at 15 00 47](https://user-images.githubusercontent.com/6655696/76219853-ca3cb480-6216-11ea-85f9-11b32eaddede.png)
![Screenshot 2020-03-09 at 15 07 52](https://user-images.githubusercontent.com/6655696/76221006-ae3a1280-6218-11ea-86f6-51f75db81667.png)

Running this using a newly created app with `flutter create`

```
Flutter 1.15.19-pre.17 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 5b0a79dbdb (13 hours ago) • 2020-03-08
21:16:01 -0400
Engine • revision 981c03631e
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
```

Chrome console has one relevant error

```js
main.dart.js:10925 DevTools exception: [NullError] NoSuchMethodError: method not found: '_trackFuture$1$2' on null
main.dart.js:10928 
main.dart.js:10935 TypeError: Cannot read property '_trackFuture$1$2' of null
    at main.dart.js:59084
    at _wrapJsFunctionForAsync_closure.$protected (main.dart.js:3597)
    at _wrapJsFunctionForAsync_closure.call$2 (main.dart.js:21758)
    at Object._asyncStartSync (main.dart.js:3562)
    at TimelineService.updateListeningState$1 (main.dart.js:59113)
    at main.dart.js:55914
    at _wrapJsFunctionForAsync_closure.$protected (main.dart.js:3597)
    at _wrapJsFunctionForAsync_closure.call$2 (main.dart.js:21758)
    at Object._asyncStartSync (main.dart.js:3562)
    at HtmlTimelineScreen._resumeFrameRecording$0 (main.dart.js:55921)
```

**Comment by kenzieschmoll** [comment]
The exception in the console suggests that the running device lost connection. `_trackFuture` is called on a VM service object, which is only set to null if the vm service is closed. If you try again and make sure the device is connected, the issue should be resolved.

If you're ever suspecting that your device is not connected, check the console from where you launched the Flutter app. You should see a message "Lost connection to device" or similar, if the connection is lost.

**Comment by guidezpl** [comment]
That was likely the case. I've tried it again. This time, no error in the console but the issue persists.

**Comment by kenzieschmoll** [comment]
What version of DevTools are you on?

**Comment by guidezpl** [comment]
```
Version Information
Flutter:
1.15.19-pre.17 • channel master • https://github.com/flutter/flutter.git
Framework:
revision 5b0a79dbdb • 2020-03-08 21:16:01 -0400
Engine:
revision 981c03631e
Dart SDK:
2.8.0-dev.12.0.flutter-9983424a3c
DevTools:
0.2.3
```

**Comment by kenzieschmoll** [comment]
Could you go to the Observatory timeline and see which flags are enabled (checkboxes across the top of the Observatory timeline)?

**Comment by guidezpl** [comment]
![Screenshot 2020-03-09 at 15 42 26](https://user-images.githubusercontent.com/6655696/76225316-9e243200-621c-11ea-80b6-5b0b82fa88d5.png)

Also, if these flags matter: 
![Screenshot 2020-03-09 at 15 41 46](https://user-images.githubusercontent.com/6655696/76225251-851b8100-621c-11ea-9206-fca2c61a5c89.png)

**Comment by kenzieschmoll** [comment]
Looks like the timeline flags are not being set properly. As a temporary workaround, you can enable the flags from the Observatory timeline and that will enable them for DevTools. If you select "Flutter Developer" or "Dart Developer" from the Observatory timeline, the flags you need should be enabled.

**Comment by kenzieschmoll** [comment]
As part of the solution to this, we should probably expose the timeline recording options from the DevTools timeline (just like they are exposed from Observatory). Perhaps we could show this option, and other advanced settings in an advanced or settings popup.

**Comment by andcea** [comment]
Is there a temporary fix for this?
I'm unable to get my timeline to work with "Show frames".
I've tried to set "Flutter Developer" or "Dart Developer" in the Observatory timeline but it has no effect on the "Show frames" timeline. 

```
Flutter:
1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework:
revision d3ed9ec945 • 2020-04-06 14:07:34 -0700
Engine:
revision c9506cb8e9
Dart SDK:
2.8.0-dev.18.0.flutter-eea9717938
DevTools:
0.1.13
```

**Comment by kenzieschmoll** [comment]
Are there any errors in the Chrome Dev Console? If you set the flags in observatory, and then come back to DevTools and refresh the page, does that work? If not, try restarting your app and restarting DevTools.

**Comment by andcea** [comment]
I have since restarted the app many times, and upgraded Flutter to the latest Beta version (1.17.0-3.2.pre).

I'm still getting an empty timeline. Flags in the observatory are checked by default (Flutter developer), but even toggling them and then refreshing the timeline does nothing (I do see data in the observatory though).

And I'm only seeing warnings in the console:
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
main.dart.js:12371 DevTools version 0.2.3.
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:60662/packages/ansi_up/ansi_up.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:60662/packages/split/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:60662/main.dart.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:60662/packages/primer_css/primer.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
main.dart.js:12371 [{"event":"app.devToolsReady"}]
```

**Comment by kenzieschmoll** [comment]
If you uncheck the "show frames" box, and record a timeline, do you see timeline events? The thread name that we check for has changed on the latest version of Flutter. My guess is that you are using a version of Flutter where the graphics thread is named 'raster' and the version of DevTools you are using is checking for a thread named 'gpu'. 

If my guess is correct, downgrading flutter to flutter stable may give you a temporary workaround. The next released version of DevTools will address the thread name inconsistencies.

**Comment by andcea** [comment]
The timeline without "Show frames" works fine.

Is the next version of DevTools going to be sync'd with the Flutter stable release?

**Comment by kenzieschmoll** [comment]
No, you should be able to use flutter master with the next release.

**Comment by andcea** [comment]
Does this mean that the timeline is going to be broken in the next stable release?

**Comment by hallidev** [comment]
I'm having the exact same issue as @andcea and it's making troubleshooting my issue very difficult. I've tried the same suggestions laid out above with no luck. Is there really no workaround for this?

**Comment by kenzieschmoll** [comment]
@hallidev I think your issue may be a different [issue](https://github.com/flutter/devtools/issues/1879) than the timeline recorders not being set. I just submitted a fix for the other issue which will be included in the next release. As a workaround, I would recommend trying the Flutter Web version of DevTools by clicking the "beaker" button in the top right of DevTools. This version is in Alpha, but we plan to be shipping the Flutter Web version by default soon.

**Comment by hallidev** [comment]
I should have mentioned in my above comment - the timeline is also empty for me in the alpha web tools.

**Comment by kenzieschmoll** [comment]
closing as obsolete - cannot reproduce the issue, and timeline recorders are now configurable from DevTools. If you are still experiencing this issue with the latest version of DevTools, we are happy to help you debug further.
